version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: lunora_database
    restart: always
    environment:
      POSTGRES_DB: lunora_living
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: raunit123
    ports:
      - "5433:5432"
    volumes:
      - lunora_db_volume_v3:/var/lib/postgresql/data

volumes:
  lunora_db_volume_v3: